name: 'Squared Suppliers' 
markdown: kramdown
highligther: pygments
timezone: CST
exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib','vendor', 'Rakefile', 's3_website.yml']
relative_permalinks: false
url: https://www.SquaredSuppliers.com
author: 'Jordan Beacham'
api_key: OTE4NmJjMzMtMjRlMy00NzE5LTgzOGQtMWU4YzAwNDBiZWQzNjM2NDE3MjAyNDYzMDE4MTQ0
gems:
    - jekyll-feed
sass:
  style: compressed
collections:
  products:
    output: true
  assets:
    output: false